# 端末ごとに微調整が必要な項目を設定
# このファイルを複製し、"config.yml"に名前を変更する

baton:
  # バトンパスするかどうか
  start: True
  stop: False
  # 開始時の回転秒数
  rotation: 5

# red_find.py用
# left_motor, right_motor, sleep の順番
motor:
  # 回避するかどうか
  motor: False
  # 障害物回避1/3
  1-l: 0.2
  1-r: 0.1
  1-s: 1.5

  # 障害物回避2/3
  2-l: 0.1
  2-r: 0.22
  2-s: 1.5

  # 障害物回避3/3
  3-l: 0.12
  3-r: 0.2
  3-s: 1.5
